const express = require('express');
const jwt = require('jsonwebtoken');
const { ObjectId } = require('mongodb');

function oid(v){try{return new ObjectId(String(v));}catch(_){return null;}}
function secret(){const v=String(process.env.JWT_ACCESS_SECRET||'').trim();if(v.length<32)throw new Error('JWT_ACCESS_SECRET chưa cấu hình an toàn.');return v;}
function createDispatchAdminRouter({getDb,getDispatch,getNotifications}){
  const r=express.Router();
  r.use(async(req,res,next)=>{try{const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return res.status(401).json({message:'Thiếu Access Token quản trị.'});const p=jwt.verify(h.slice(7).trim(),secret());const id=oid(p.sub||p.userId);if(!id)return res.status(401).json({message:'Token không hợp lệ.'});const u=await getDb().collection('users').findOne({_id:id,roles:'ADMIN'});if(!u)return res.status(403).json({message:'Không có quyền ADMIN.'});req.admin=u;next();}catch(e){return res.status(401).json({message:'Phiên quản trị không hợp lệ.'});}});
  r.get('/config',async(req,res)=>{try{return res.json(await getDispatch().getConfig());}catch(e){return res.status(500).json({message:e.message});}});
  r.put('/config',async(req,res)=>{try{return res.json(await getDispatch().saveConfig(req.body||{},req.admin._id));}catch(e){return res.status(400).json({message:e.message});}});
  r.get('/live',async(req,res)=>{try{const db=getDb();const bookings=await db.collection('bookings').find({status:{$in:['SEARCHING','OFFERED','DRIVER_ASSIGNED','DRIVER_ARRIVING','DRIVER_ARRIVED','IN_PROGRESS']}}).sort({createdAt:-1}).limit(100).toArray();return res.json(bookings.map(b=>({id:String(b._id),code:b.bookingCode,status:b.status,dispatchEngine:b.dispatchEngine||null,pickup:b.pickup?.address||'',destination:b.destination?.address||'',driverId:b.driverId?String(b.driverId):null,createdAt:b.createdAt})));}catch(e){return res.status(500).json({message:e.message});}});
  r.get('/bookings/:id',async(req,res)=>{try{return res.json(await getDispatch().detail(req.params.id));}catch(e){return res.status(400).json({message:e.message});}});
  r.post('/bookings/:id/retry',async(req,res)=>{try{const id=oid(req.params.id);if(!id)return res.status(400).json({message:'Booking id không hợp lệ.'});await getDb().collection('bookings').updateOne({_id:id,status:'NO_DRIVER'},{$set:{status:'SEARCHING','dispatchEngine.status':'ADMIN_REQUEUED',updatedAt:new Date()},$unset:{'dispatchEngine.completedAt':''}});return res.json(await getDispatch().dispatchWithRetry(req.params.id,{reset:true,adminId:req.admin._id}));}catch(e){return res.status(400).json({message:e.message});}});
  r.post('/bookings/:id/next-round',async(req,res)=>{try{return res.json(await getDispatch().dispatchBooking(req.params.id,{reset:false,adminId:req.admin._id}));}catch(e){return res.status(400).json({message:e.message});}});
  r.post('/bookings/:id/send-to-driver',async(req,res)=>{try{const id=oid(req.params.id);if(!id)return res.status(400).json({message:'Booking id không hợp lệ.'});await getDb().collection('bookings').updateOne({_id:id,status:'NO_DRIVER'},{$set:{status:'SEARCHING','dispatchEngine.status':'ADMIN_REQUEUED',updatedAt:new Date()},$unset:{'dispatchEngine.completedAt':''}});return res.json(await getDispatch().manualOffer(req.params.id,req.body?.driverId,req.admin._id));}catch(e){return res.status(400).json({message:e.message});}});
  r.post('/bookings/:id/cancel-offers',async(req,res)=>{try{await getDispatch().cancelBooking(req.params.id,'ADMIN_CANCELLED');return res.json({ok:true});}catch(e){return res.status(400).json({message:e.message});}});
  r.get('/cooldowns',async(req,res)=>{try{const rows=await getDb().collection('driver_cooldowns').find({expiresAt:{$gt:new Date()}}).sort({expiresAt:1}).limit(200).toArray();return res.json(rows.map(x=>({...x,id:String(x._id),driverId:String(x.driverId),bookingId:x.bookingId?String(x.bookingId):null})));}catch(e){return res.status(500).json({message:e.message});}});
  r.delete('/cooldowns/:driverId',async(req,res)=>{try{const id=oid(req.params.driverId);if(!id)return res.status(400).json({message:'Driver id không hợp lệ.'});await getDb().collection('driver_cooldowns').deleteMany({driverId:id});return res.json({ok:true});}catch(e){return res.status(500).json({message:e.message});}});
  r.get('/push',async(req,res)=>{try{const db=getDb();const rows=await db.collection('notification_outbox').find({}).sort({createdAt:-1}).limit(Math.min(200,Number(req.query.limit||100))).toArray();const stats=await db.collection('notification_outbox').aggregate([{$group:{_id:'$status',count:{$sum:1}}}]).toArray();return res.json({configured:getNotifications().isConfigured(),stats:Object.fromEntries(stats.map(x=>[x._id,x.count])),rows:rows.map(x=>({...x,id:String(x._id),targetId:String(x.targetId)}))});}catch(e){return res.status(500).json({message:e.message});}});
  r.post('/push/:id/retry',async(req,res)=>{try{return res.json(await getNotifications().retryNotification(req.params.id));}catch(e){return res.status(400).json({message:e.message});}});
  return r;
}
module.exports={createDispatchAdminRouter};
